# Maintainer: Clove Twilight <clove@doughmination.gay>
#
# The MorvaneOS GRUB theme. theme/ is generated by tools/build.py and committed,
# so building the package needs nothing but the repo.

pkgname=morvane-grub-theme
pkgver=1.0.0
pkgrel=1
pkgdesc='MorvaneOS GRUB theme (Twilight Peaks)'
arch=(any)
url='https://github.com/MorvaneOS/morvane-grub-theme'
license=(custom OFL-1.1)  # custom: artwork license TBD (see LICENSE); OFL: the bundled fonts
depends=(grub)
# artools' buildiso copies /usr/share/grub/themes/artix into every ISO, so the
# theme is installed there too and this package stands in for Artix's.
provides=(artix-grub-theme)
conflicts=(artix-grub-theme)
replaces=(artix-grub-theme)

package() {
  local theme
  for theme in morvane artix; do
    install -d "$pkgdir/usr/share/grub/themes/$theme"
    install -m644 "$startdir"/theme/* -t "$pkgdir/usr/share/grub/themes/$theme/"
  done
  install -Dm644 "$startdir/morvane-grub-theme.hook" -t "$pkgdir/usr/share/libalpm/hooks/"
  install -Dm644 "$startdir/LICENSE" "$startdir/OFL.txt" -t "$pkgdir/usr/share/licenses/$pkgname/"
}
