#!/usr/bin/env python3
"""Builds the MorvaneOS GRUB theme into theme/.

    python tools/build.py [path/to/morvane-assets]

Needs Python packages fonttools and pillow, plus rsvg-convert (librsvg) and
grub-mkfont (grub). The logo comes from the MorvaneOS/assets repo
(default: ../../../morvane-assets, i.e. ~/projects/morvane-assets).
"""

import io
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'theme'
CACHE = ROOT / 'tools' / '.cache'
ASSETS = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT.parent.parent.parent / 'morvane-assets'

# MorvaneOS palette (see MorvaneOS/assets README)
PASTEL = '#F4A6C6'
LAVENDER = '#B9A3E6'
NIGHT = '#120C16'
PANEL = '#1A1220'  # the boot list's box, a step lighter than the background
BORDER = '#3A2B3F'
TEXT = '#D9CFE0'
MUTED = '#8F7F96'

FONT_URL = 'https://github.com/google/fonts/raw/main/ofl/jetbrainsmono/JetBrainsMono%5Bwght%5D.ttf'
# (weight, point size) pairs; GRUB fonts are bitmaps, one file per size
FONTS = [(400, 14), (400, 16), (400, 20), (700, 20)]


def rgba(hex_colour: str, alpha: int = 255) -> tuple[int, int, int, int]:
	return (int(hex_colour[1:3], 16), int(hex_colour[3:5], 16), int(hex_colour[5:7], 16), alpha)


def nine_slice(prefix: str, radius: int, fill: str, border: str | None = None, pad_x: int | None = None) -> None:
	"""A rounded box cut into GRUB's 9 pieces (prefix_nw.png ... prefix_c.png).

	GRUB draws the corners as-is and stretches the edges and centre, so the box
	grows to any size with crisp rounded corners. The side pieces' width is also
	the inner padding before the text starts, so pad_x widens them.
	"""
	scale = 4  # draw big, then shrink, for smooth corners
	r = radius
	p = pad_x or radius
	w, h = p * 2 + 1, r * 2 + 1
	big = Image.new('RGBA', (w * scale, h * scale), (0, 0, 0, 0))
	draw = ImageDraw.Draw(big)
	box = (0, 0, w * scale - 1, h * scale - 1)
	if border:
		draw.rounded_rectangle(box, radius=r * scale, fill=rgba(border))
		inset = scale  # 1 px border
		draw.rounded_rectangle(
			(inset, inset, w * scale - 1 - inset, h * scale - 1 - inset),
			radius=(r - 1) * scale,
			fill=rgba(fill),
		)
	else:
		draw.rounded_rectangle(box, radius=r * scale, fill=rgba(fill))
	img = big.resize((w, h), Image.LANCZOS)

	pieces = {
		'nw': (0, 0, p, r),
		'n': (p, 0, p + 1, r),
		'ne': (p + 1, 0, w, r),
		'w': (0, r, p, r + 1),
		'c': (p, r, p + 1, r + 1),
		'e': (p + 1, r, w, r + 1),
		'sw': (0, r + 1, p, h),
		's': (p, r + 1, p + 1, h),
		'se': (p + 1, r + 1, w, h),
	}
	for name, crop in pieces.items():
		img.crop(crop).save(OUT / f'{prefix}_{name}.png')


def build_fonts() -> None:
	CACHE.mkdir(parents=True, exist_ok=True)
	vf = CACHE / 'JetBrainsMono-VF.ttf'
	if not vf.exists():
		urllib.request.urlretrieve(FONT_URL, vf)
	for weight in sorted({w for w, _ in FONTS}):
		static = CACHE / f'JetBrainsMono-{weight}.ttf'
		if not static.exists():
			font = instantiateVariableFont(TTFont(vf), {'wght': weight}, updateFontNames=True)
			buf = io.BytesIO()
			font.save(buf)
			static.write_bytes(buf.getvalue())
	for weight, size in FONTS:
		style = 'bold' if weight == 700 else 'regular'
		subprocess.run(
			['grub-mkfont', '-s', str(size), '-o', str(OUT / f'jetbrains_mono_{style}_{size}.pf2'), str(CACHE / f'JetBrainsMono-{weight}.ttf')],
			check=True,
		)


def build_logo() -> None:
	src = ASSETS / 'svg' / 'mark' / 'pastel.svg'
	if not src.exists():
		sys.exit(f'Logo not found: {src} (pass the MorvaneOS/assets path as an argument)')
	subprocess.run(['rsvg-convert', '-w', '112', '-h', '112', '-o', str(OUT / 'logo.png'), str(src)], check=True)


THEME = f'''# MorvaneOS GRUB theme: Twilight Peaks
# Generated by tools/build.py; edit that, not this file.

title-text: ""
desktop-color: "{NIGHT}"
terminal-font: "JetBrains Mono Regular 16"
terminal-box: "box_*.png"

+ image {{
	left = 50%-56
	top = 12%
	width = 112
	height = 112
	file = "logo.png"
}}

+ boot_menu {{
	left = 50%-320
	top = 12%+148
	width = 640
	height = 38%
	item_font = "JetBrains Mono Regular 20"
	selected_item_font = "JetBrains Mono Bold 20"
	item_color = "{TEXT}"
	selected_item_color = "{NIGHT}"
	item_height = 38
	item_padding = 14
	item_spacing = 4
	icon_width = 0
	icon_height = 0
	item_icon_space = 0
	menu_pixmap_style = "box_*.png"
	selected_item_pixmap_style = "select_*.png"
	scrollbar = true
	scrollbar_width = 6
	scrollbar_thumb = "thumb_*.png"
}}

+ label {{
	id = "__timeout__"
	left = 0
	top = 100%-76
	width = 100%
	align = "center"
	color = "{LAVENDER}"
	font = "JetBrains Mono Regular 16"
	text = "Booting in %d seconds"
}}

+ label {{
	left = 0
	top = 100%-44
	width = 100%
	align = "center"
	color = "{MUTED}"
	font = "JetBrains Mono Regular 14"
	text = "Up/Down to choose · Enter to boot · e to edit · c for a command line"
}}
'''


if __name__ == '__main__':
	shutil.rmtree(OUT, ignore_errors=True)
	OUT.mkdir(parents=True)
	nine_slice('box', radius=10, fill=PANEL, border=BORDER)
	nine_slice('select', radius=6, fill=PASTEL, pad_x=14)
	nine_slice('thumb', radius=3, fill=PASTEL)
	build_logo()
	build_fonts()
	(OUT / 'theme.txt').write_text(THEME)
	print(f'Built {len(list(OUT.iterdir()))} files in {OUT}')
